### ISSUE TITLE
subprocess.CalledProcessError: Command 'pairix /home/zjin/neat1/13.TAD_boundary_pile_up/mcool/.HiCLift/c2c12.pairs.gz' returned non-zero exit status 127.

### ISSUE THREAD

**Issue by gavinjzg** [XiaoTaoWang/HiCLift#12]
Hi！
I am facing an issuea bout the output format.
when i use the pairs ,it's ok.
![image](https://user-images.githubusercontent.com/52107940/236462710-3d9ba84c-bfa8-44ed-8240-9ff236397773.png)
but when i use the hic ,It shows an error like subprocess.CalledProcessError: Command 'pairix /home/zjin/neat1/13.TAD_boundary_pile_up/mcool/.pairliftover/c2c12.pairs.gz' returned non-zero exit status 127
(peakachu) HiCLift --input test.mm10.100kb.cool --input-format cooler --out-pre c2c12  --output-format hic  --out-chromsizes ./new_mm10_gsize_NoMTY  --in-assembly mm21 --out-assembly mm21 --memory 40G
root                      INFO    @ 05/05/23 14:41:29: 
# ARGUMENT LIST:
# Input path = test.mm10.100kb.cool
# Input format = cooler
# Output prefix = c2c12
# Output format = hic
# Chromosome Sizes of the output assembly = ./new_mm10_gsize_NoMTY
# Generate contact maps at 11 resolutions = False
# Input assembly = mm21
# Output assembly = mm21
# Chain file = None
# Temporary Dir = .HiCLift
# Allocated memory = 40G
# Number of Processes = 8
# Log file name = HiCLift.log
root                      INFO    @ 05/05/23 14:41:39: Trying to perform a pure format conversion without liftover ...
HiCLift.utilities         INFO    @ 05/05/23 14:41:39: Writing headers ...
HiCLift.utilities         INFO    @ 05/05/23 14:41:39: Dumping contact pairs from test.mm10.100kb.cool ...
/bin/sh: pairix: command not found
Traceback (most recent call last):
  File "/home/zjin/anaconda3/envs/peakachu/bin/HiCLift", line 137, in <module>
    run()
  File "/home/zjin/anaconda3/envs/peakachu/bin/HiCLift", line 110, in run
    liftover(
  File "/home/zjin/anaconda3/envs/peakachu/lib/python3.8/site-packages/HiCLift/utilities.py", line 213, in liftover
    subprocess.check_call(' '.join(command), shell=True)
  File "/home/zjin/anaconda3/envs/peakachu/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pairix /home/zjin/neat1/13.TAD_boundary_pile_up/mcool/.HiCLift/c2c12.pairs.gz' returned non-zero exit status 127.
How should I solve this problem?Thank you for your help and time,

**Comment by XiaoTaoWang** [comment]
Hi, the error message indicates that the pairix command cannot be found. Have you installed HiCLift according to the guidelines provided here https://github.com/XiaoTaoWang/HiCLift#installation?
