### ISSUE TITLE
How to draw a beautiful HIC map

### ISSUE THREAD

**Issue by songxh1996** [XiaoTaoWang/HiCLift#14]
Hello, Professor Wang, thank you for providing so much useful software. I tried a lot of software, such as fanc,hicexplorer, but did not draw the hic map I wanted. I was so lucky to see this beautiful HIC map in you. But I didn't find out how you drew it, whether I missed what it was.
How do you draw a beautiful HIC map? Which script is used

![fig1 svg](https://github.com/XiaoTaoWang/HiCLift/assets/119746508/c4cb4693-88d3-4309-80ed-8c07986dd028)

**Comment by XiaoTaoWang** [comment]
Hi, you may refer to this page as a reference https://xiaotaowang.github.io/TADLib/visualize.html

**Comment by songxh1996** [comment]
Thank you very much for your help. When I finished running the test data according to your guidance, it was successful. But when I used my own data, it failed. I can't figure out why.


my cool file 
##########.hic2.cool
hicConvertFormat -m LD_nomt.allValidPairs.hic --inputFormat hic --outputFormat cool \
-o KR_matrix.cool -r 10000 --correction_name KR
###########hic-pro result covert cool
cooler load -f coo LD_nomt_10000_abs.bed \
LD_nomt_10000_iced.matrix \
10000.cool --count-as-float


>>> vis = Triangle('GM12878-MboI.hg19.cool::10000', '21', 45000000, 46500000)
>>> vis = Triangle('10000.cool::10000', 'NC_059157.1', 4500000, 4650000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/songxianhan/miniconda3/envs/test/lib/python3.7/site-packages/tadlib/visualize/heatmaps.py", line 18, in __init__
    self.clr = cooler.Cooler(uri)
  File "/home/songxianhan/miniconda3/envs/test/lib/python3.7/site-packages/cooler/api.py", line 85, in __init__
    self._refresh()
  File "/home/songxianhan/miniconda3/envs/test/lib/python3.7/site-packages/cooler/api.py", line 106, in _refresh
    raise KeyError(err_msg) from None
KeyError: "No cooler found at: 10000.cool. Coolers found in ['/']. Use '::' to specify a group path"
>>>

**Comment by XiaoTaoWang** [comment]
Can you try the following command instead:

    vis = Triangle('10000.cool', 'NC_059157.1', 4500000, 4650000)

**Comment by songxh1996** [comment]
When I use this code, the error persists.

>>> vis = Triangle('40000.cool', 'NC_059157.1', 4500000, 4650000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/songxianhan/miniconda3/envs/tset/lib/python3.7/site-packages/tadlib/visualize/heatmaps.py", line 18, in __init__
    self.clr = cooler.Cooler(uri)
  File "/home/songxianhan/miniconda3/envs/tset/lib/python3.7/site-packages/cooler/api.py", line 85, in __init__
    self._refresh()
  File "/home/songxianhan/miniconda3/envs/tset/lib/python3.7/site-packages/cooler/api.py", line 106, in _refresh
    raise KeyError(err_msg) from None
KeyError: "No cooler found at: 40000.cool. Coolers found in ['/40000']. Use '::' to specify a group path"
>>>

**Comment by XiaoTaoWang** [comment]
Can you show the result after you execute the following command?

    $ cooler ls 40000.cool
